"""Lab stimuli for SWATTER: looming discs and the controls they must beat.

The standard experiment (Ache et al. 2019) presents a disc of half-size r
approaching at speed v, parameterised by r/v in milliseconds, with t_c the
collision time. Its angular size is

    theta(t) = 2 arctan( r / (v * (t_c - t)) )

and the same expression with a plus sign in the denominator gives the receding
control. Three more controls come free from the same formula family:

    expanding   r/v constant, disc grows          <- the escape trigger
    receding    negative r/v, disc shrinks        <- must stay silent
    translating constant angular size, no growth  <- must stay silent
    dimming     constant size, contrast falls     <- equal-flux control

The point of generating all four here is that criterion 1 of the plan
("GF-proxy fires only for expansion") is only meaningful if the controls are
generated by the same code path as the stimulus. A separate hand-written
control is a control that can accidentally differ in some other way.

Every stimulus returns luminance samples on an eye, in fly units, plus the
ground truth the brain stage will be judged against.

Usage:
    python offline/loom.py --summary
    python offline/loom.py --rv 20 --azimuth 90 --save /tmp/loom20.json
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import asdict, dataclass, field

import numpy as np

# Fly-scale defaults from the plan's stimulus mapping table.
FLY_LENGTH_MM = 2.5
SWATTER_HALF_WIDTH_MM = 50.0
HOVER_HEIGHT_MM = 150.0

# Lab r/v sweep. The plan uses these four; they span the published range.
RV_MS = (10.0, 20.0, 40.0, 80.0)

# Collision sits this far past the end of the trial, so every sample is
# pre-collision and theta never reaches the degenerate 180 deg.
COLLISION_OVERSHOOT = 1.2

# Where in the expanding run-up the flat-size controls take their size from.
CONTROL_MATCH_FRACTION = 0.8

STIMULUS_KINDS = ("expanding", "receding", "translating", "dimming")


@dataclass
class EyeGeometry:
    """One eye: azimuths of the sample columns, in degrees.

    Angles run over one eye's hemifield. The two eyes are mirror images, so the
    whole scene is rendered by calling the sampler twice with mirrored azimuths.
    """

    azimuth_deg: np.ndarray
    acceptance_deg: float = 6.0  # roughly one inter-column spacing

    @property
    def n_columns(self) -> int:
        return int(self.azimuth_deg.size)

    @classmethod
    def hexagonal_lattice(cls, n_columns: int = 721, span_deg: float = 170.0) -> "EyeGeometry":
        """721 columns across the visual field, denser near the horizon.

        A uniform azimuth grid is close enough for stimulus bookkeeping and keeps
        the eye renderer independent of any lattice spec. Swap this for the real
        flyvis column directions when the optic lobe lands.
        """
        azimuth = np.linspace(-span_deg / 2, span_deg / 2, n_columns)
        return cls(azimuth_deg=azimuth, acceptance_deg=float(span_deg / n_columns))


@dataclass
class Loom:
    """A single trial's stimulus parameters, in fly-scale units."""

    kind: str = "expanding"
    rv_ms: float = 20.0
    azimuth_deg: float = 0.0
    elevation_deg: float = 90.0  # straight up, so it looms rather than approaches
    half_size_mm: float = SWATTER_HALF_WIDTH_MM
    duration_ms: float = 400.0
    dt_ms: float = 0.5
    contrast: float = 1.0
    background: float = 1.0  # bright sky
    foreground: float = 0.0  # dark swatter: dark looms are the classic trigger

    @property
    def n_steps(self) -> int:
        return max(2, int(round(self.duration_ms / self.dt_ms)) + 1)

    @property
    def t_c_ms(self) -> float:
        """Collision time, measured back from stimulus onset.

        For an expanding disc this is when the swatter reaches the fly. It sits
        `COLLISION_OVERSHOOT` past the end of the trial so that every sample is
        strictly pre-collision: the escape decision has to be made before impact,
        and a sample at exactly t_c has theta = 180 deg, which is a degenerate
        "the disc covers the whole eye" reading rather than a measurement.

        For a receding disc the same value is the *extrapolated* collision time
        in the past: the disc was heading toward the fly and passed, so it is
        already moving away at t = 0.
        """
        return self.duration_ms * COLLISION_OVERSHOOT

    def time_ms(self) -> np.ndarray:
        return np.linspace(0.0, self.duration_ms, self.n_steps)

    def angular_size_deg(self) -> np.ndarray:
        """theta(t), per stimulus kind, in degrees.

        Expanding uses the plan's formula directly:

            theta(t) = 2 arctan( r/v / (t_c - t) )

        Receding is the same disc travelling the other way, so its distance grows
        rather than shrinking towards zero:

            theta(t) = 2 arctan( r/v / (t + t_c) )

        which starts at exactly the same angle as the expanding trial and decays
        monotonically to zero. Taking the absolute value of the expanding formula
        instead would make receding identical to expanding, which would silently
        delete criterion 1 from the suite.

        Translating and dimming hold angular size constant at `control_size_deg`,
        so they differ from the expanding trial only in the time course.
        """
        t = self.time_ms()

        if self.kind == "expanding":
            remaining = np.maximum(self.t_c_ms - t, 1e-6)
            return np.degrees(2.0 * np.arctan(self.rv_ms / remaining))

        if self.kind == "receding":
            return np.degrees(2.0 * np.arctan(self.rv_ms / (t + self.t_c_ms)))

        return np.full_like(t, self.control_size_deg())

    def control_size_deg(self) -> float:
        """Angular size held constant by the translating and dimming controls.

        Taken from the expanding trial late in its run-up, so the control is a
        clearly visible disc of a size the eye really responds to, and the only
        thing it lacks is growth. A control matched to the expanding trial's
        mid-trial size would be well under a degree here and would pass by being
        too small to see, which tests nothing.
        """
        t = self.duration_ms * CONTROL_MATCH_FRACTION
        remaining = max(self.t_c_ms - t, 1e-6)
        return float(np.degrees(2.0 * np.arctan(self.rv_ms / remaining)))

    def luminance(self, eye: EyeGeometry) -> np.ndarray:
        """(n_steps, n_columns) luminance as the eye sees it.

        A dark disc against a bright sky: each column is dark when the disc
        covers it, and the transition is smoothed by the column's acceptance
        angle, so the edges are not infinitely sharp.
        """
        theta = self.angular_size_deg()
        centre = self.azimuth_deg
        # Everything here stays in degrees: theta and acceptance_deg are degrees,
        # and mixing in radians silently makes every column look covered.
        offset = np.abs(eye.azimuth_deg - centre)
        offset = np.minimum(offset, 360.0 - offset)  # wrap to [0, 180]

        covered = np.clip((theta[:, None] / 2.0 - offset[None, :]) / eye.acceptance_deg + 0.5, 0.0, 1.0)

        if self.kind == "dimming":
            # Equal-flux: the disc stays put but its contrast decays to nothing.
            fade = np.clip(1.0 - t_normalised(self), 0.0, 1.0)[:, None]
            return self.background + (self.foreground - self.background) * covered * fade

        if self.kind == "translating":
            # Constant size, moving across the field.
            sweep = centre + np.linspace(-1.0, 1.0, self.n_steps) * 40.0
            offset = np.abs(eye.azimuth_deg[None, :] - sweep[:, None])
            offset = np.minimum(offset, 360.0 - offset)
            covered = np.clip((theta[:, None] / 2.0 - offset) / eye.acceptance_deg + 0.5, 0.0, 1.0)

        level = self.foreground + (1.0 - self.foreground) * (1.0 - self.contrast)
        return self.background + (level - self.background) * covered

    def ground_truth(self) -> dict[str, float]:
        """What a correct escape circuit must report for this stimulus."""
        theta = self.angular_size_deg()
        return {
            "kind": self.kind,
            "should_escape": self.kind == "expanding",
            "angular_size_start_deg": float(theta[0]),
            # Reported separately from the peak: for a receding disc the peak is
            # its starting size, so printing start -> peak makes a shrinking
            # stimulus look flat.
            "angular_size_end_deg": float(theta[-1]),
            "peak_angular_size_deg": float(theta.max()),
            "peak_size_time_ms": float(self.time_ms()[int(np.argmax(theta))]),
            "size_rate_deg_per_ms": float(np.gradient(theta, self.dt_ms).max()),
        }


def t_normalised(loom: Loom) -> np.ndarray:
    t = loom.time_ms()
    return (t - t[0]) / max(t[-1] - t[0], 1e-6)


def build_suite(
    rv_ms: tuple[float, ...] = RV_MS,
    azimuths: tuple[float, ...] | None = None,
) -> list[Loom]:
    """The plan's criterion sweep: 4 r/v x 8 azimuths x 4 stimulus types.

    Azimuths are spaced evenly over the full circle so criterion 4 (heading
    biased away from the stimulus) is measured against a uniform stimulus field
    rather than a hand-picked set of directions. The two eyes are mirror images,
    so one eye's hemisphere covers the azimuth range.
    """
    full = tuple(float(a) for a in np.linspace(0.0, 360.0, 8, endpoint=False))
    azimuth_set = azimuths if azimuths else full
    suite: list[Loom] = []
    for kind in STIMULUS_KINDS:
        for rv in rv_ms:
            for azimuth in azimuth_set:
                suite.append(Loom(kind=kind, rv_ms=rv, azimuth_deg=azimuth))
    return suite


def summarise(loom: Loom) -> dict:
    eye = EyeGeometry.hexagonal_lattice()
    luminance = loom.luminance(eye)
    return {
        **asdict(loom),
        **loom.ground_truth(),
        "n_columns": eye.n_columns,
        "luminance_min": float(luminance.min()),
        "luminance_max": float(luminance.max()),
        # Measured on the last sample, matching angular_size_end_deg. Taking it
        # at argmax would report the receding disc's widest moment.
        "fraction_dark_at_end": float((luminance[-1] < 0.5).mean()),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--kind", default="expanding", choices=STIMULUS_KINDS)
    parser.add_argument("--rv", type=float, default=20.0, help="r/v in ms")
    parser.add_argument("--azimuth", type=float, default=0.0)
    parser.add_argument("--duration", type=float, default=400.0)
    parser.add_argument("--dt", type=float, default=0.5)
    parser.add_argument("--suite", action="store_true", help="print the full criterion sweep")
    parser.add_argument("--summary", action="store_true", help="print one line per stimulus kind")
    parser.add_argument("--save", type=str, help="write the suite as JSON")
    args = parser.parse_args()

    if args.suite or args.save or args.summary:
        suite = build_suite()
        if args.summary:
            for kind in STIMULUS_KINDS:
                sample = next(s for s in suite if s.kind == kind and s.rv_ms == 20.0)
                row = summarise(sample)
                print(f"{kind:<12} rv={row['rv_ms']:>5.0f}ms  theta {row['angular_size_start_deg']:6.2f}"
                      f" -> {row['angular_size_end_deg']:6.2f} deg  "
                      f"size_rate={row['size_rate_deg_per_ms']:7.4f} deg/ms  "
                      f"should_escape={str(row['should_escape']):<5} "
                      f"dark_cols@end={row['fraction_dark_at_end']:.2f}")
            return 0
        print(f"suite: {len(suite)} trials = {len(RV_MS)} r/v x 8 azimuths x "
              f"{len(STIMULUS_KINDS)} stimulus types")
        by_kind: dict[str, int] = {}
        for loom in suite:
            by_kind[loom.kind] = by_kind.get(loom.kind, 0) + 1
        for kind, count in by_kind.items():
            sample = next(s for s in suite if s.kind == kind)
            row = summarise(sample)
            print(f"  {kind:<12} n={count:<4} peak {row['peak_angular_size_deg']:6.2f} deg "
                  f"at {row['peak_size_time_ms']:6.1f} ms  should_escape={row['should_escape']}  "
                  f"dark_cols={row['fraction_dark_at_end']:.2f}")
        if args.save:
            with open(args.save, "w") as handle:
                json.dump([summarise(s) for s in suite], handle, indent=2)
            print(f"wrote {args.save}")
        return 0

    loom = Loom(
        kind=args.kind,
        rv_ms=args.rv,
        azimuth_deg=args.azimuth,
        duration_ms=args.duration,
        dt_ms=args.dt,
    )
    row = summarise(loom)
    print(json.dumps(row, indent=2, default=float))

    theta = loom.angular_size_deg()
    marks = [0, len(theta) // 4, len(theta) // 2, 3 * len(theta) // 4, len(theta) - 1]
    print("\ntheta(t) = 2 arctan(r/v / (t_c - t))")
    for i in marks:
        print(f"  t={loom.time_ms()[i]:7.2f} ms   theta={theta[i]:7.3f} deg")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
